#define skibidi	void
#define rizz    int
#define cap	    bool
#define cooked  auto
#define flex    for
#define yeet	return
#define edging	if
#define amogus	else
#define goon	while
#define bruh	break
#define grind	continue
#define chad	float
#define gigachad	double
#define yap	    char
#define grimace	const
#define sigma	case
#define based	default
#define mewing	do
#define gyatt	enum
#define whopper	extern
#define cringe	goto
#define giga	long
#define edgy	register
#define soy	    short
#define nut 	signed
#define maxxing	sizeof
#define salty	static
#define gang	struct
#define ohio	switch
#define chungus	union
#define nonut	unsigned
#define schizo	volatile
#define yapping printf
